spring.application.name=order-service


spring.datasource.url=jdbc:h2:mem:orderdb

spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8083

spring.kafka.bootstrap-servers=localhost:9092

#Sending the OrderCreatedEvent as JSON

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#open the circuit if the failure rate increased more than the 50% : Like ok,x,x,x,ok Here the failure rate is 60% hence circuit will open
resilience4j.circuitbreaker.instances.productServiceCB.failure-rate-threshold=50
#It does not evaluate the failure rate until 5 calls are made
resilience4j.circuitbreaker.instances.productServiceCB.minimum-number-of-calls=5
#Base the failure rate on the last 10 calls.
resilience4j.circuitbreaker.instances.productServiceCB.sliding-window-size=10
#Keep circuit open 10s before trying again
resilience4j.circuitbreaker.instances.productServiceCB.wait-duration-in-open-state=10s
#only allows 3 calls when it is in half-open-state and determine to close or open the circuit
resilience4j.circuitbreaker.instances.productServiceCB.permitted-number-of-calls-in-half-open-state=3

resilience4j.retry.instances.productServiceRetry.max-attempts=3
resilience4j.retry.instances.productServiceRetry.wait-duration=20s
